version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "14191:14191"
      - "8000:8000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    links:
      - server
    ports:
      - "8080:80"